name: Publish

on: workflow_dispatch

jobs:
  publish:
    name: Create release

    permissions:
      contents: write
      packages: write
      actions: write

    strategy:
      matrix:
        node-version: [ 20.x ]
        os:
          [
            { name: 'linux', image: 'ubuntu-latest' },
            { name: 'windows', image: 'windows-latest' },
            { name: 'macos', image: 'macos-latest' },
          ]

    runs-on: ${{ matrix.os.image }}

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Make and publish (${{ matrix.os.name }})
        run: yarn run release
        env:
          GITHUB_TOKEN: ${{ github.token }}